name: CI

on: [push, pull_request]

jobs:
  build_windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Do not convert LF to CRLF on checkout
        run: |
          git config core.autocrlf false
          git checkout .
      - name: Build setup
        run: ./setup-build.sh
        shell: bash
      
      - name: Build
        run: ./build.sh
        shell: bash
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*