name: CI

on: [push, pull_request]

jobs:
  build_windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Do not convert LF to CRLF on checkout
        run: |
          git config core.autocrlf false
          git checkout .

      - name: Add vcvarsall to PATH
        run: echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build setup
        run: ./setup-build.sh
        shell: bash
      
      - name: Build
        run: ./build.sh
        shell: bash
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*